package utils

const (
	// -------------- COACHING PROGRAM
	GET_ALL_MASTER_COACHING_PROGRAM = "GET_ALL_MASTER_COACHING_PROGRAM"
	GET_ALL_COACHING_PROGRAM        = "GET_ALL_COACHING_PROGRAM"
	INSERT_COACHING_PROGRAM         = "INSERT_COACHING_PROGRAM"
	CONFIRM_COACHING_PROGRAM        = "CONFIRM_COACHING_PROGRAM"

	// -------------- SCHEDULE
	GET_ALL_SCHEDULE       = "GET_ALL_SCHEDULE"
	UPDATE_USER_SCHEDULE   = "UPDATE_USER_SCHEDULE"
	UPDATE_MENTOR_SCHEDULE = "UPDATE_MENTOR_SCHEDULE"

	// -------------- MENTOR
	REGISTER_MENTOR = "REGISTER_MENTOR"

	// -------------- CLASS
	GET_ALL_CLASS_QURAN = "GET_ALL_CLASS_QURAN"
)
