package utils

const (
	// -------------- COACHING PROGRAM
	GET_ALL_MASTER_COACHING_PROGRAM = "GET_ALL_MASTER_COACHING_PROGRAM"
	GET_ALL_COACHING_PROGRAM        = "GET_ALL_COACHING_PROGRAM"
	INSERT_COACHING_PROGRAM         = "INSERT_COACHING_PROGRAM"
	CONFIRM_COACHING_PROGRAM        = "CONFIRM_COACHING_PROGRAM"
	// -------------- SCHEDULE
	GET_ALL_SCHEDULE       = "GET_ALL_SCHEDULE"
	UPDATE_USER_SCHEDULE   = "UPDATE_USER_SCHEDULE"
	UPDATE_MENTOR_SCHEDULE = "UPDATE_MENTOR_SCHEDULE"
	// -------------- PAYMENT
	INSERT_PAYMENT_QURAN  = "INSERT_PAYMENT_QURAN"
	UPLOAD_PAYMENT_QURAN  = "UPLOAD_PAYMENT_QURAN"
	CONFIRM_PAYMENT_QURAN = "CONFIRM_PAYMENT_QURAN"
	// -------------- MENTOR
	REGISTER_MENTOR = "REGISTER_MENTOR"
	// -------------- CLASS
	GET_ALL_CLASS_QURAN = "GET_ALL_CLASS_QURAN"
	// -------------- USER CLASS
	GET_ALL_USER_CLASS_QURAN          = "GET_ALL_USER_CLASS_QURAN"
	GET_ALL_USER_CLASS_DETAIL_QURAN   = "GET_ALL_USER_CLASS_DETAIL_QURAN"
	GET_ALL_USER_CLASS_SCHEDULE_QURAN = "GET_ALL_USER_CLASS_SCHEDULE_QURAN"
	INSERT_USER_CLASS_QURAN_SCHEDULE  = "INSERT_USER_CLASS_QURAN_SCHEDULE"
	UPDATE_USER_CLASS_QURAN_SCHEDULE  = "UPDATE_USER_CLASS_QURAN_SCHEDULE"
	UPDATE_USER_CLASS_QURAN_PROGRESS  = "UPDATE_USER_CLASS_QURAN_PROGRESS"
	// -------------- USER CLASS
	GET_ALL_LEARNING_QURAN = "GET_ALL_LEARNING_QURAN"
	// -------------- RATING
	GET_ALL_RATING_CLASS_QURAN = "GET_ALL_RATING_CLASS_QURAN"
	GIVE_RATING_CLASS_QURAN    = "GIVE_RATING_CLASS_QURAN"
	// -------------- PROMOTION
	GET_ALL_PROMOTION        = "GET_ALL_PROMOTION"
	GET_ALL_PROMOTION_HEADER = "GET_ALL_PROMOTION_HEADER"
	CLAIM_PROMOTION          = "CLAIM_PROMOTION"
	// -------------- COUNTRY CODE
	GET_ALL_COUNTRY_CODE = "GET_ALL_COUNTRY_CODE"
	// -------------- EVENT
	GET_ALL_EVENT            = "GET_ALL_EVENT"
	INSERT_FORM_CLASS_INTENS = "INSERT_FORM_CLASS_INTENS"
)
